package com.blacksmithdreamapps.presentgo

import android.content.Context
import android.content.Context.MODE_PRIVATE
import android.database.sqlite.SQLiteDatabase
/**
 * Developed and designed by Dream Apps Blacksmith
 * Code author is Boskin Kostya
 * On 014 14.03.2018.
 */
class DataBaseHelper

(private val myContext: Context){

    fun  handleDb() : SQLiteDatabase
    {
        val myDatabase = myContext.openOrCreateDatabase("MyGifts", MODE_PRIVATE, null)
        myDatabase.execSQL("CREATE TABLE IF NOT EXISTS `en` (\n" +
                "\t`id`\tINTEGER NOT NULL DEFAULT 1 PRIMARY KEY AUTOINCREMENT UNIQUE,\n" +
                "\t`Family`\tINTEGER,\n" +
                "\t`Friends`\tINTEGER,\n" +
                "\t`Colleagues`\tINTEGER,\n" +
                "\t`Beloved`\tINTEGER,\n" +
                "\t`Superiors`\tINTEGER,\n" +
                "\t`Person_i_hate`\tINTEGER,\n" +
                "\t`Male`\tINTEGER,\n" +
                "\t`Female`\tINTEGER,\n" +
                "\t`Child`\tINTEGER,\n" +
                "\t`Teenager`\tINTEGER,\n" +
                "\t`Adult`\tINTEGER,\n" +
                "\t`Elderly`\tINTEGER,\n" +
                "\t`Budget_minimal`\tINTEGER,\n" +
                "\t`Budget_low`\tINTEGER,\n" +
                "\t`Budget_middle`\tINTEGER,\n" +
                "\t`Budget_middle_plus`\tINTEGER,\n" +
                "\t`Budget_high`\tINTEGER,\n" +
                "\t`Birthday`\tINTEGER,\n" +
                "\t`Anniversary`\tINTEGER,\n" +
                "\t`Holiday`\tINTEGER,\n" +
                "\t`Graduation`\tINTEGER,\n" +
                "\t`Wedding`\tINTEGER,\n" +
                "\t`Just_because`\tINTEGER,\n" +
                "\t`Stranger`\tINTEGER,\n" +
                "\t`One_time_seen`\tINTEGER,\n" +
                "\t`Acquaintance`\tINTEGER,\n" +
                "\t`Comrade`\tINTEGER,\n" +
                "\t`Close`\tINTEGER,\n" +
                "\t`Name`\tTEXT,\n" +
                "\t`Description`\tTEXT,\n" +
                "\t`Image`\tTEXT\n" +
                ")");
        myDatabase.execSQL("INSERT OR REPLACE INTO `en` (id,Family,Friends,Colleagues,Beloved,Superiors,Person_i_hate,Male,Female,Child,Teenager,Adult,Elderly,Budget_minimal,Budget_low,Budget_middle,Budget_middle_plus,Budget_high,Birthday,Anniversary,Holiday,Graduation,Wedding,Just_because,Stranger,One_time_seen,Acquaintance,Comrade,Close,Name,Description,Image) VALUES (0,'true','true','false','false','false','true','true','true','false','false','true','true','true','true','true','false','false','false','false','true','false','true','true','true','true','true','true','true','humidifier','smells good, easy to use, cheap enough','https://i5.walmartimages.com/asr/77e71f98-a377-4a1b-890d-f99b2318ea29_1.8d1ea0c74df02f4a9d1d608f54976dc7.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF'),\n" +
                " (1,'true','true','true','true','false','false','true','true','false','true','true','false','false','true','true','true','false','true','false','true','false','true','true','false','true','true','true','true','headphones','easy to buy, everybody needs them, plays music :)','https://static.eldorado.ru/photos/71/712/096/18/new_71209618_l_1475743981.jpeg'),\n" +
                " (2,'true','true','true','true','false','true','true','true','false','true','true','true','false','false','true','true','true','true','true','true','false','true','true','true','true','true','true','true','perfume\n" +
                "','smells good, huge diversity, easy to buy','https://images.ua.prom.st/2831522_w0_h0_1153.jpg'),\n" +
                " (3,'true','true','true','true','false','false','true','true','false','true','true','true','true','true','true','true','true','true','true','true','false','true','true','false','false','true','true','true','cozy scarf','sweet, warm, beautiful','https://i1.rozetka.ua/goods/2418130/28196537_images_2418130185.jpg'),\n" +
                " (4,'true','true','false','true','false','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','souvenir','beautiful, linked with memories, may be anything','https://www.tourprom.ru/site_media/images/souvenir/big-ben-suvenir-iz-londona_1.jpg'),\n" +
                " (5,'true','true','true','true','true','false','true','true','false','true','true','true','false','true','true','true','true','true','true','true','false','true','false','false','false','true','true','true','trip together','laugh, adventures, memories','http://www.phototopic.ru/uploads/posts/2013-08/1376423049_foto-puteshestvie-nogami-vpered_2.jpg'),\n" +
                " (6,'true','true','true','true','false','false','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','false','false','false','false','false','true','true','mobile phone','extra needed, useful, you can make selfies:)','http://vashgolos.net/photo/techno/70288_0.jpg'),\n" +
                " (7,'true','true','true','true','false','false','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','false','false','false','false','false','true','true','tablet','like a mobile, but bigger:), but bigger:(','https://skobka.com.ua/upload/medialibrary/5ed/5ed52db91e1bb65bf9e99f3af5d61a0d.jpg'),\n" +
                " (8,'true','true','true','true','false','true','true','true','false','false','true','true','false','true','true','true','false','true','true','true','false','true','true','false','true','true','true','true','bathrobe','warm, sweet, great gift for any human!','https://media.togas.com/media/catalog/product/cache/8/image/1600x/040ec09b1e35df139433887a97daa66f/e/m/emborio_main_1.jpg'),\n" +
                " (10,'true','true','false','true','true','false','true','true','false','false','true','true','false','false','true','true','true','false','true','true','true','true','false','false','false','false','true','true','permit for a sanatorium','best for families, in summer, has own program','http://www.ayda.ru/images/pics/8/h-25061-_1.jpg'),\n" +
                " (11,'false','true','false','true','false','false','true','true','false','true','true','false','false','true','true','true','true','true','true','true','true','true','true','false','false','true','true','true','photocam','high-quality photos, you look like pro, many-many-many photos','https://i2.wp.com/funfoto.me/wp-content/uploads/2017/11/1641431791-1.jpg?fit=800%2C800'),\n" +
                " (12,'true','true','true','false','true','true','true','true','true','true','true','true','true','true','true','true','false','true','false','true','true','true','false','true','true','true','true','false','table lamp','work in evening, your eyes are safe, very useful','http://lampa.dn.ua/img2/nastolnaja-lampa/nastolnaja-lampa-vt-069-black.jpg'),\n" +
                " (13,'true','true','true','true','false','false','true','true','true','true','true','false','true','true','true','false','false','true','true','true','false','false','true','true','true','true','true','true','ride on skates','skate on ice, best with friends, you can play hockey','http://www.novosibirskgid.ru/image/1364301867_886.jpg'),\n" +
                " (14,'false','true','false','true','false','false','true','true','false','true','false','false','true','true','true','true','true','true','false','true','false','false','true','true','true','true','true','true','skateboard','you can do skateboarding, any time you want, perform tricks','http://www.championnet.ru/spree/products/46778/original/03%D0%A1%D0%BA%D0%B5%D0%B9%D1%82%D0%B1%D0%BE%D1%80%D0%B4_Larsen_City-2__%D1%8031%D1%858.jpg?1455878689'),\n" +
                " (15,'true','true','true','false','false','false','true','true','true','true','true','false','false','true','true','true','false','true','false','true','false','false','false','false','false','true','true','true','designer flash drive','looks rather pretty, cheap, can be handmade','http://www.usb-fleshki.com.ua/cont/img/cat/big/dizaynerskaya-fleshka-domik.jpg?1483778060'),\n" +
                " (16,'true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','organizer','write what you think, manage time, little psyhologist sometimes','http://didaktor.ru/wp-content/uploads/2012/08/notopersonalorganizer-300x225.jpg'),\n" +
                " (17,'true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','false','false','true','false','true','true','false','false','true','true','true','true','true','decoration','looks pretty, creates own style, field for experiments','https://i.pinimg.com/originals/e7/0a/ca/e70aca2a95a3258d3ab7f35e3d6cf227.jpg'),\n" +
                " (18,'true','true','true','true','false','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','true','magic ball','it is magic, it is a ball, it is a magic ball!','https://www.lewisblack.com/sites/default/files/magic-ball-i-dont-give-a-shit-800_0.jpg'),\n" +
                " (19,'false','true','true','true','false','true','true','true','true','true','true','false','true','true','true','false','false','true','false','true','false','false','true','true','true','true','true','true','cozy slippers','you legs feels cozy:), it is very comfortable, suites everyone','http://www.barmaley-sakh.ru/file/1773.jpg'),\n" +
                " (20,'true','true','true','true','false','true','true','true','true','true','true','true','true','true','true','false','false','true','true','true','false','true','true','true','true','true','true','true','cup','drink tea, drink coffee, drink anything you want','https://prazdnik-shop.com.ua/20486-large_default/chashka-batareyka.jpg'),\n" +
                " (21,'true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','false','false','true','true','true','true','false','true','true','true','true','true','true','twister game','play with friends, it is fun, laugh at every step','http://lotosplazaptz.ru/images/cms/data/fotoalbomy/prazdnik_zazhzheniya_novogodnih_ognej_yolochka_gori2/img_1750.jpg'),\n" +
                " (22,'true','true','false','true','false','true','true','true','false','true','true','false','false','true','true','true','false','true','false','true','false','false','true','true','true','true','true','true','monopoly game','play with friends, it is fun, build your business or empire','https://s3-eu-west-1.amazonaws.com/mosigra.product.main/525/945/IMG_8689_800x500.jpg'),\n" +
                " (23,'true','true','false','true','false','true','true','true','false','true','true','false','false','true','true','true','false','true','false','true','false','false','true','true','true','true','true','true','plad','soft, warm, sweet\n" +
                "','https://ucarecdn.com/52d5dcc3-df47-4212-8988-a783fb8952f1/'),\n" +
                " (24,'true','true','true','true','false','false','true','true','false','false','true','true','true','true','false','false','false','true','true','true','false','true','false','false','false','true','true','true','a set of salt cellars or pepper','put here spices, good gift for family, can be designed in original way','https://ae01.alicdn.com/kf/HTB1L0NSHpXXXXbjaXXXq6xXFXXX3/-.jpg_640x640.jpg'),\n" +
                " (25,'true','true','true','false','true','false','true','true','false','false','true','true','false','false','true','true','true','false','false','true','false','true','false','false','false','false','false','true','appliances','good gift for family, helps by house, makes dirty job','https://pisces.bbystatic.com/image2/BestBuy_US/store/ee/2016/app/pr/SOL-1819-majors-labor-day-sale/SOL-1819-samsung-stainless-showcase-slideins.jpg;maxHeight=309;maxWidth=457'),\n" +
                " (26,'true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','false','true','true','true','true','true','original alarm clock','it can be original form, original sound, makes your wake up in original way','https://img01-olxua.akamaized.net/img-olxua/582313232_1_644x461_podarok-aktsiyasovremennyy-i-originalnyy-budilnik-ct390-thomson-kremenchug.jpg'),\n" +
                " (27,'true','false','false','true','false','false','false','true','false','false','true','true','false','false','true','true','true','true','true','true','false','true','true','false','false','false','false','true','romantic trip','live, love, laugh','https://media.jaa.su/wp-content/uploads/2012/06/46.jpg'),\n" +
                " (28,'true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','bouquet of flowers','easy to find, smells good, can be a sign of smth bigger','https://flor2u.ru/images/uploads/conversion/bb3/bb38ecceec8d0b21ff510f4a9b16b70d/flor.detail.gallery.jpg'),\n" +
                " (29,'true','true','true','true','false','false','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','a kilo of candies','they are sweet, tasty, never is enough of them','https://optomamarf.ru/files/8b9/8b91783007b542dccbce2de211e5f7bd.jpg'),\n" +
                " (30,'true','true','true','true','false','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','tickets for the concert','jump, sing, relax','https://d3c1jucybpy4ua.cloudfront.net/data/49674/big_picture/concert-tickets.jpg?1476965087'),\n" +
                " (31,'true','true','true','true','false','true','true','true','false','true','true','true','false','true','true','true','false','true','false','true','false','false','true','true','true','true','true','true','thermo cup','saves heat, very practical, good for tourism','https://cdn.27.ua/499/4e/74/544372_5.jpeg'),\n" +
                " (32,'true','true','false','true','false','false','false','true','false','true','true','true','true','true','true','false','false','false','false','true','false','false','false','false','false','false','false','true','Hair straightener','straights hair, rather cheap, easy to buy ','https://cdn3.bigcommerce.com/s-an64sgsrfr/products/124/images/449/duvolle_straightener_impulse_1_x1280__41116.1468511521.500.500.jpg?c=2'),\n" +
                " (33,'true','true','false','false','false','false','true','true','false','true','true','true','false','false','true','true','true','true','false','true','false','false','false','false','true','true','true','true','thermal underwear','suits for spotrs, warms when cold, comfortable','http://www.craft.od.ua/wa-data/public/shop/products/82/28/2882/images/2280/2280.970.jpg'),\n" +
                " (34,'true','true','true','true','false','false','true','true','false','true','true','false','true','true','true','true','false','true','false','true','true','false','false','true','true','true','true','true','portable speaker','music everywhere, cheap, best for picnics','https://img1.moyo.ua/img/categories/6452/6452_1473863012_72.jpg'),\n" +
                " (35,'true','true','true','true','false','false','true','true','true','true','true','true','true','true','true','false','false','true','true','true','false','false','false','false','false','true','true','true','Night Light Projector','makes light, beautiful, stylish','https://images.ua.prom.st/907273662_w0_h0_holigoo_2pcs_f__oon_starry.jpg'),\n" +
                " (36,'true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','powerbank','charges, makes you autonomous, can be stylish','http://i01.appmifile.com/webfile/globalimg/my/2014/main/dianyuan/7.jpg?20131204'),\n" +
                " (37,'true','true','false','true','false','false','true','true','true','true','true','false','false','true','true','true','false','true','true','true','false','false','false','false','false','false','true','true','Kigurumi','sweet, cute, funny','https://images-na.ssl-images-amazon.com/images/I/81dI2Y-PHML._UL1500_.jpg'),\n" +
                " (38,'true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','Monopod','popularity, selfies, easy to buy','https://images-na.ssl-images-amazon.com/images/I/71%2Bc0DbOKhL._SL1500_.jpg'),\n" +
                " (39,'true','true','false','true','false','false','true','true','false','true','true','true','false','true','true','true','true','false','false','true','true','false','true','false','false','true','true','true','sleeping bag','camping trips, warms when cold, autonomy','https://avatars.mds.yandex.net/get-mpic/195452/img_id8201692694962997977/9hq'),\n" +
                " (40,'true','true','true','true','false','true','true','true','false','true','true','true','true','true','true','true','false','true','false','true','false','false','true','false','false','true','true','true','Fitness Bracelet','phone syncronization, great functionality, manages time','http://mylifegadgets.com/wp-content/uploads/2017/04/GBlife-ID107-Sports-Smart-Bracelet-with-Heart-Rate-Monitor-Remote-Camera-Fitness-Tracker-Watch-0.jpg'),\n" +
                " (41,'true','true','true','true','false','true','true','true','false','true','true','true','true','true','true','true','false','true','false','true','false','false','true','false','false','true','true','true','Smart watches','phone syncronization, great functionality, manages time','https://i1.wp.com/2kita.com.ua/wp-content/uploads/2017/11/%D0%A1%D0%BC%D0%B0%D1%80%D1%82-%D1%87%D0%B0%D1%81%D1%8B-Smart-Watch-V9-Red-3.jpg?fit=320%2C320&ssl=1'),\n" +
                " (42,'true','true','true','true','false','true','true','true','false','true','true','true','true','true','true','true','false','true','true','true','false','false','true','true','true','true','true','true','Bombs for bath','they are funny, laught, smells good','http://otzyvy.pro/image.php?nocache=1&img=uploads/reviews/2015-11/8f6c5069f55610b348b5bb888793d2ef.jpg'),\n" +
                " (43,'true','true','true','true','false','false','true','true','false','true','true','true','false','true','true','true','false','true','true','true','true','true','true','false','false','true','true','true','Jewelry Box','saves valueable things, can be handmade, practical','http://www.hit-dekor.ru/images/detailed/6/04593.jpg'),\n" +
                " (44,'true','true','true','true','false','true','true','true','false','true','true','true','true','true','true','false','false','true','true','true','false','true','true','true','true','true','true','true','Aromatic lamp','smells good, for special events, good mood all day','http://www.trustedhealthproducts.com/blog/wp-content/uploads/2016/07/aroma-lamp-300x200.jpg'),\n" +
                " (45,'true','true','true','false','false','false','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','Certificate for the photo shoot','photoes, instagram, impressions','https://static.lightfield.com.ua/storage/image/bdb3ad52fa5cddf0f56b0a179d5519d6fcf0e73a.jpg'),\n" +
                " (46,'true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','sunglasses','protects from sun, looks pathetic, makes style','http://cdn.shopify.com/s/files/1/1609/2039/products/Untitled-1_37ff9af7-3f18-4bfa-a853-d0df6763523e_grande.jpg?v=1508802906');\n")

        myDatabase.execSQL("CREATE TABLE IF NOT EXISTS `ru` (\n" +
                "\t`id`\tINTEGER NOT NULL DEFAULT 1 PRIMARY KEY AUTOINCREMENT UNIQUE,\n" +
                "\t`Family`\tINTEGER,\n" +
                "\t`Friends`\tINTEGER,\n" +
                "\t`Colleagues`\tINTEGER,\n" +
                "\t`Beloved`\tINTEGER,\n" +
                "\t`Superiors`\tINTEGER,\n" +
                "\t`Person_i_hate`\tINTEGER,\n" +
                "\t`Male`\tINTEGER,\n" +
                "\t`Female`\tINTEGER,\n" +
                "\t`Child`\tINTEGER,\n" +
                "\t`Teenager`\tINTEGER,\n" +
                "\t`Adult`\tINTEGER,\n" +
                "\t`Elderly`\tINTEGER,\n" +
                "\t`Budget_minimal`\tINTEGER,\n" +
                "\t`Budget_low`\tINTEGER,\n" +
                "\t`Budget_middle`\tINTEGER,\n" +
                "\t`Budget_middle_plus`\tINTEGER,\n" +
                "\t`Budget_high`\tINTEGER,\n" +
                "\t`Birthday`\tINTEGER,\n" +
                "\t`Anniversary`\tINTEGER,\n" +
                "\t`Holiday`\tINTEGER,\n" +
                "\t`Graduation`\tINTEGER,\n" +
                "\t`Wedding`\tINTEGER,\n" +
                "\t`Just_because`\tINTEGER,\n" +
                "\t`Stranger`\tINTEGER,\n" +
                "\t`One_time_seen`\tINTEGER,\n" +
                "\t`Acquaintance`\tINTEGER,\n" +
                "\t`Comrade`\tINTEGER,\n" +
                "\t`Close`\tINTEGER,\n" +
                "\t`Name`\tTEXT,\n" +
                "\t`Description`\tTEXT,\n" +
                "\t`Image`\tTEXT\n" +
                ");");

        myDatabase.execSQL("INSERT OR REPLACE INTO `ru` (id,Family,Friends,Colleagues,Beloved,Superiors,Person_i_hate,Male,Female,Child,Teenager,Adult,Elderly,Budget_minimal,Budget_low,Budget_middle,Budget_middle_plus,Budget_high,Birthday,Anniversary,Holiday,Graduation,Wedding,Just_because,Stranger,One_time_seen,Acquaintance,Comrade,Close,Name,Description,Image) VALUES (0,'true','true','false','false','false','true','true','true','false','false','true','true','true','true','true','false','false','false','false','true','false','true','true','true','true','true','true','true','освежитель воздуха','хорошо пахнет, прост в использовании, достаточно дешев','https://i5.walmartimages.com/asr/77e71f98-a377-4a1b-890d-f99b2318ea29_1.8d1ea0c74df02f4a9d1d608f54976dc7.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF'),\n" +
                " (1,'true','true','true','true','false','false','true','true','false','true','true','false','false','true','true','true','false','true','false','true','false','true','true','false','true','true','true','true','наушники','легко купить, нужны всем, играют музыку :)','https://static.eldorado.ru/photos/71/712/096/18/new_71209618_l_1475743981.jpeg'),\n" +
                " (2,'true','true','true','true','false','true','true','true','false','true','true','true','false','false','true','true','true','true','true','true','false','true','true','true','true','true','true','true','духи','хорошо пахнет, огромный выбор, легко купить','https://images.ua.prom.st/2831522_w0_h0_1153.jpg'),\n" +
                " (3,'true','true','true','true','false','false','true','true','false','true','true','true','true','true','true','true','true','true','true','true','false','true','true','false','false','true','true','true','уютный шарф','приятный, теплый, красивый','https://i1.rozetka.ua/goods/2418130/28196537_images_2418130185.jpg'),\n" +
                " (4,'true','true','false','true','false','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','Сувенир','красивый, напоминает о чем-то, может быть любой вещью','https://www.tourprom.ru/site_media/images/souvenir/big-ben-suvenir-iz-londona_1.jpg'),\n" +
                " (5,'true','true','true','true','true','false','true','true','false','true','true','true','false','true','true','true','true','true','true','true','false','true','false','false','false','true','true','true','путешествовие вместе','смех, приключения, воспоминания','http://www.phototopic.ru/uploads/posts/2013-08/1376423049_foto-puteshestvie-nogami-vpered_2.jpg'),\n" +
                " (6,'true','true','true','true','false','false','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','false','false','false','false','false','true','true','мобильный телефон','очень нужен, полезный, можно делать селфи:)','http://vashgolos.net/photo/techno/70288_0.jpg'),\n" +
                " (7,'true','true','true','true','false','false','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','false','false','false','false','false','true','true','Таблетка','как телефон, но больше:), но больше:(','https://skobka.com.ua/upload/medialibrary/5ed/5ed52db91e1bb65bf9e99f3af5d61a0d.jpg'),\n" +
                " (8,'true','true','true','true','false','true','true','true','false','false','true','true','false','true','true','true','false','true','true','true','false','true','true','false','true','true','true','true','банный халат','теплый, милый, отличный подарок для любого!','https://media.togas.com/media/catalog/product/cache/8/image/1600x/040ec09b1e35df139433887a97daa66f/e/m/emborio_main_1.jpg'),\n" +
                " (10,'true','true','false','true','true','false','true','true','false','false','true','true','false','false','true','true','true','false','true','true','true','true','false','false','false','false','true','true','путевка в санаторий','лучше всего для семей, в летнее время, с программой','http://www.ayda.ru/images/pics/8/h-25061-_1.jpg'),\n" +
                " (11,'false','true','false','true','false','false','true','true','false','true','true','false','false','true','true','true','true','true','true','true','true','true','true','false','false','true','true','true','камера','Крутые фотографии, вы похожи на профи, много-много-много фотографий','https://i2.wp.com/funfoto.me/wp-content/uploads/2017/11/1641431791-1.jpg?fit=800%2C800'),\n" +
                " (12,'true','true','true','false','true','true','true','true','true','true','true','true','true','true','true','true','false','true','false','true','true','true','false','true','true','true','true','false','настольная лампа','можно работать по вечерам, глаза в безопасности, очень полезна','http://lampa.dn.ua/img2/nastolnaja-lampa/nastolnaja-lampa-vt-069-black.jpg'),\n" +
                " (13,'true','true','true','true','false','false','true','true','true','true','true','false','true','true','true','false','false','true','true','true','false','false','true','true','true','true','true','true','покатушки на коньках','катания на льду, лучше всего с друзьями, можно играть в хоккей','http://www.novosibirskgid.ru/image/1364301867_886.jpg'),\n" +
                " (14,'false','true','false','true','false','false','true','true','false','true','false','false','true','true','true','true','true','true','false','true','false','false','true','true','true','true','true','true','скейтборд','можно кататься, когда угодно, делать трюки','http://www.championnet.ru/spree/products/46778/original/03%D0%A1%D0%BA%D0%B5%D0%B9%D1%82%D0%B1%D0%BE%D1%80%D0%B4_Larsen_City-2__%D1%8031%D1%858.jpg?1455878689'),\n" +
                " (15,'true','true','true','false','false','false','true','true','true','true','true','false','false','true','true','true','false','true','false','true','false','false','false','false','false','true','true','true','дизайнерская флешка','выглядит симпатично, недорого, можно сделать самому','http://www.usb-fleshki.com.ua/cont/img/cat/big/dizaynerskaya-fleshka-domik.jpg?1483778060'),\n" +
                " (16,'true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','органайзер','записывайте мысли, управляете временем, немного психолог','http://didaktor.ru/wp-content/uploads/2012/08/notopersonalorganizer-300x225.jpg'),\n" +
                " (17,'true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','false','false','true','false','true','true','false','false','true','true','true','true','true','украшение','выглядит симпатично, создайте стиль, поле для экспериментов','https://i.pinimg.com/originals/e7/0a/ca/e70aca2a95a3258d3ab7f35e3d6cf227.jpg'),\n" +
                " (18,'true','true','true','true','false','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','true','волшебный шар','это магия, это шар, это магический шар!','https://www.lewisblack.com/sites/default/files/magic-ball-i-dont-give-a-shit-800_0.jpg'),\n" +
                " (19,'false','true','true','true','false','true','true','true','true','true','true','false','true','true','true','false','false','true','false','true','false','false','true','true','true','true','true','true','уютные тапочки','ногам уютно:), очень удобные, подходят всем','http://www.barmaley-sakh.ru/file/1773.jpg'),\n" +
                " (20,'true','true','true','true','false','true','true','true','true','true','true','true','true','true','true','false','false','true','true','true','false','true','true','true','true','true','true','true','кружка','пейте чай, пейте кофе, пейте что угодно!','https://prazdnik-shop.com.ua/20486-large_default/chashka-batareyka.jpg'),\n" +
                " (21,'true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','false','false','true','true','true','true','false','true','true','true','true','true','true','твистер','играйте с друзьями, веселье, смех на каждом шагу','http://lotosplazaptz.ru/images/cms/data/fotoalbomy/prazdnik_zazhzheniya_novogodnih_ognej_yolochka_gori2/img_1750.jpg'),\n" +
                " (22,'true','true','false','true','false','true','true','true','false','true','true','false','false','true','true','true','false','true','false','true','false','false','true','true','true','true','true','true','монополия','играйте с друзьями, веселье, постройте свой бизнес или империю','https://s3-eu-west-1.amazonaws.com/mosigra.product.main/525/945/IMG_8689_800x500.jpg'),\n" +
                " (23,'true','true','false','true','false','true','true','true','false','true','true','false','false','true','true','true','false','true','false','true','false','false','true','true','true','true','true','true','плед','мягкий, теплый, уютный\n" +
                "','https://ucarecdn.com/52d5dcc3-df47-4212-8988-a783fb8952f1/'),\n" +
                " (24,'true','true','true','true','false','false','true','true','false','false','true','true','true','true','false','false','false','true','true','true','false','true','false','false','false','true','true','true','набор солешниц','для специй, подарок для семьи, может иметь оригинальный дизайн','https://ae01.alicdn.com/kf/HTB1L0NSHpXXXXbjaXXXq6xXFXXX3/-.jpg_640x640.jpg'),\n" +
                " (25,'true','true','true','false','true','false','true','true','false','false','true','true','false','false','true','true','true','false','false','true','false','true','false','false','false','false','false','true','бытовая техника','отличный подарок семье, помогает в быту, делает сложную работу','https://pisces.bbystatic.com/image2/BestBuy_US/store/ee/2016/app/pr/SOL-1819-majors-labor-day-sale/SOL-1819-samsung-stainless-showcase-slideins.jpg;maxHeight=309;maxWidth=457'),\n" +
                " (26,'true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','false','true','true','true','true','true','оригинальный будильник','может быть оригинальной формы, с оригинальным звуком, будет оригинально:)','https://img01-olxua.akamaized.net/img-olxua/582313232_1_644x461_podarok-aktsiyasovremennyy-i-originalnyy-budilnik-ct390-thomson-kremenchug.jpg'),\n" +
                " (27,'true','false','false','true','false','false','false','true','false','false','true','true','false','false','true','true','true','true','true','true','false','true','true','false','false','false','false','true','романтическое путешествие','живи, люби, смейся','https://media.jaa.su/wp-content/uploads/2012/06/46.jpg'),\n" +
                " (28,'true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','букет цветов','легко найти, приятно пахнет, может быть чем-то большим','https://flor2u.ru/images/uploads/conversion/bb3/bb38ecceec8d0b21ff510f4a9b16b70d/flor.detail.gallery.jpg'),\n" +
                " (29,'true','true','true','true','false','false','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','килограмм конфет','сладкие, вкусные, их всегда мало','https://optomamarf.ru/files/8b9/8b91783007b542dccbce2de211e5f7bd.jpg'),\n" +
                " (30,'true','true','true','true','false','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','билеты на концерт','прыгй, пой, отдыхай','https://d3c1jucybpy4ua.cloudfront.net/data/49674/big_picture/concert-tickets.jpg?1476965087'),\n" +
                " (31,'true','true','true','true','false','true','true','true','false','true','true','true','false','true','true','true','false','true','false','true','false','false','true','true','true','true','true','true','термочашка','сохраняет тепло, очень практичен, подходит для туризма','https://cdn.27.ua/499/4e/74/544372_5.jpeg'),\n" +
                " (32,'true','true','false','true','false','false','false','true','false','true','true','true','true','true','true','false','false','false','false','true','false','false','false','false','false','false','false','true','Выпрямитель для волос','выпрямляет волосы, достаточно недорогой, легко найти','https://cdn3.bigcommerce.com/s-an64sgsrfr/products/124/images/449/duvolle_straightener_impulse_1_x1280__41116.1468511521.500.500.jpg?c=2'),\n" +
                " (33,'true','true','false','false','false','false','true','true','false','true','true','true','false','false','true','true','true','true','false','true','false','false','false','false','true','true','true','true','термобелье','подходит для спорта, согревает в холод, комфортная','http://www.craft.od.ua/wa-data/public/shop/products/82/28/2882/images/2280/2280.970.jpg'),\n" +
                " (34,'true','true','true','true','false','false','true','true','false','true','true','false','true','true','true','true','false','true','false','true','true','false','false','true','true','true','true','true','портативная колонка','музыка везде, недорого, отлично подходит для пикников','https://img1.moyo.ua/img/categories/6452/6452_1473863012_72.jpg'),\n" +
                " (35,'true','true','true','true','false','false','true','true','true','true','true','true','true','true','true','false','false','true','true','true','false','false','false','false','false','true','true','true','Ночник-проектор ','освещает комнату, красивый, стильный','https://images.ua.prom.st/907273662_w0_h0_holigoo_2pcs_f__oon_starry.jpg'),\n" +
                " (36,'true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','павербанк','заряжает, ты автономен, может быть стильной','http://i01.appmifile.com/webfile/globalimg/my/2014/main/dianyuan/7.jpg?20131204'),\n" +
                " (37,'true','true','false','true','false','false','true','true','true','true','true','false','false','true','true','true','false','true','true','true','false','false','false','false','false','false','true','true','кингуруми','милая, забавная, смешная','https://images-na.ssl-images-amazon.com/images/I/81dI2Y-PHML._UL1500_.jpg'),\n" +
                " (38,'true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','true','палка для селфи','популярность, селфи, легко купить','https://images-na.ssl-images-amazon.com/images/I/71%2Bc0DbOKhL._SL1500_.jpg'),\n" +
                " (39,'true','true','false','true','false','false','true','true','false','true','true','true','false','true','true','true','true','false','false','true','true','false','true','false','false','true','true','true','спальник','походы, греет в холод, автономность','https://avatars.mds.yandex.net/get-mpic/195452/img_id8201692694962997977/9hq'),\n" +
                " (40,'true','true','true','true','false','true','true','true','false','true','true','true','true','true','true','true','false','true','false','true','false','false','true','false','false','true','true','true','фитнес трекер','синхронизация с телефоном, большой функционал, распределяет время','http://mylifegadgets.com/wp-content/uploads/2017/04/GBlife-ID107-Sports-Smart-Bracelet-with-Heart-Rate-Monitor-Remote-Camera-Fitness-Tracker-Watch-0.jpg'),\n" +
                " (41,'true','true','true','true','false','true','true','true','false','true','true','true','true','true','true','true','false','true','false','true','false','false','true','false','false','true','true','true','смарт часы','синхронизация с телефоном, большой функционал, распределяет время','https://i1.wp.com/2kita.com.ua/wp-content/uploads/2017/11/%D0%A1%D0%BC%D0%B0%D1%80%D1%82-%D1%87%D0%B0%D1%81%D1%8B-Smart-Watch-V9-Red-3.jpg?fit=320%2C320&ssl=1'),\n" +
                " (42,'true','true','true','true','false','true','true','true','false','true','true','true','true','true','true','true','false','true','true','true','false','false','true','true','true','true','true','true','бомбочки для ванной','забавные, дополнят ванну, хорошо пахнут','http://otzyvy.pro/image.php?nocache=1&img=uploads/reviews/2015-11/8f6c5069f55610b348b5bb888793d2ef.jpg'),\n" +
                " (43,'true','true','true','true','false','false','true','true','false','true','true','true','false','true','true','true','false','true','true','true','true','true','true','false','false','true','true','true','Шкатулка','хранит ценности, можно сделать самому, практична','http://www.hit-dekor.ru/images/detailed/6/04593.jpg'),\n" +
                " (44,'true','true','true','true','false','true','true','true','false','true','true','true','true','true','true','false','false','true','true','true','false','true','true','true','true','true','true','true','Ароматическая лампа','хорошо пахнет, для особых событий, дарит хорошее настроение','http://www.trustedhealthproducts.com/blog/wp-content/uploads/2016/07/aroma-lamp-300x200.jpg'),\n" +
                " (45,'true','true','true','false','false','false','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','фотосессия','фотки, инстаграм, впечатления','https://static.lightfield.com.ua/storage/image/bdb3ad52fa5cddf0f56b0a179d5519d6fcf0e73a.jpg'),\n" +
                " (46,'true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','true','true','true','true','true','true','false','true','true','true','true','true','true','очки','защита от солнца, пафосный вид, создают стиль','http://cdn.shopify.com/s/files/1/1609/2039/products/Untitled-1_37ff9af7-3f18-4bfa-a853-d0df6763523e_grande.jpg?v=1508802906');\n")




        return myDatabase

    }


}
